# Configuration file for running the test suite. Results will be at https://travis-ci.org/phpList/phplist-plugin-restapi
# whitelist
language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  # Set a custom vhost
  - sudo sed -i -e "s,/var/www,$(pwd)/vendor/phpList/phplist3/public_html,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "/DocumentRoot/i\ServerName phplist.dev" /etc/apache2/sites-available/default
  - sudo sed -i -e "/DocumentRoot/i\SetEnv ConfigFile $(pwd)/tests/travis-ci/config.php" /etc/apache2/sites-available/default
  - echo "127.0.0.1 phplist.dev" | sudo tee -a /etc/hosts
  - sudo cat /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
  - composer self-update
  - composer install --prefer-dist
  - sudo cp -f tests/travis-ci/behat.yml behat.yml
  - sudo cp -f tests/travis-ci/phpunit.xml tests/phpunit/

  # Set MySQL configuration and create the database.
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database phplisttraviscidb;'

script:
  - vendor/bin/behat
  - phpunit -c tests/phpunit/phpunit.xml tests/phpunit/restapi.php
after_failure:
  - echo "Failures detected. Outputing additional logs:"
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/mysql/error.log
